import { MigrationInterface, QueryRunner } from "typeorm";

export class createTables1667850798715 implements MigrationInterface {
    name = 'createTables1667850798715'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_d34442903fff451ea18518dbe1e"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_ce369917874b691538849a790f7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_bafb08f60d7857f4670c172a6ea"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a20f12b66b835efd3e9cdc8efa0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d1803064187c8f38e57a9c4984c"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_6e912f52513d3edc50f106778fb"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_156b59646727c4d7370e17a3454"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_52bbf2d21bdcac200def516a69d"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_461b2f6f9be2df60f173a0230bc"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_434e93481b53d8007bcf8af8b9d"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_2c6928902becf89437748914cb0"`);
        await queryRunner.query(`ALTER TABLE "requests" RENAME COLUMN "usersId" TO "userId"`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying NOT NULL, "district" character varying NOT NULL, "zipCode" character varying NOT NULL, "number" character varying, "complement" character varying, "city" character varying NOT NULL, "state" character varying NOT NULL, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams_fields_fields" ("teamsId" uuid NOT NULL, "fieldsId" uuid NOT NULL, CONSTRAINT "PK_99630d0a9ebe12c7c793dee613f" PRIMARY KEY ("teamsId", "fieldsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eeb9f45ec38a70dc96234ab959" ON "teams_fields_fields" ("teamsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a906e42264bcb3e8e9e871a992" ON "teams_fields_fields" ("fieldsId") `);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "ownersId"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "REL_ce369917874b691538849a790f"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "adressesId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "REL_a20f12b66b835efd3e9cdc8efa"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "REL_d1803064187c8f38e57a9c4984"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "teamId"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "usersId"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "fieldsId"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "participantsId"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "teamsId"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "REL_2c6928902becf89437748914cb"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "usersId"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "createdAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "isActive" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "createdAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "ownerId" uuid`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "addressId" uuid`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "UQ_c924581ed54ddae034f24955f83" UNIQUE ("addressId")`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "createdAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "createdAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "isActive" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "UQ_5fc9cddc801b973cd9edcdda42a" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "teamId" uuid`);
        await queryRunner.query(`ALTER TABLE "owners" ADD CONSTRAINT "UQ_df4ef717018c5dc7bd3f4ab0de5" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "UQ_48c0c32e6247a2de155baeaf980" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_a7d98ec4be2c842c6556188cfdc" FOREIGN KEY ("ownerId") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_c924581ed54ddae034f24955f83" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_bafb08f60d7857f4670c172a6ea" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_be846ad4b43f40acc7034ef7f40" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_5c5696b2c3c57698f890b2cbbdd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_5fc9cddc801b973cd9edcdda42a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_b5291286325dc7472d0b4c9e6dd" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams_fields_fields" ADD CONSTRAINT "FK_eeb9f45ec38a70dc96234ab9598" FOREIGN KEY ("teamsId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teams_fields_fields" ADD CONSTRAINT "FK_a906e42264bcb3e8e9e871a9928" FOREIGN KEY ("fieldsId") REFERENCES "fields"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "teams_fields_fields" DROP CONSTRAINT "FK_a906e42264bcb3e8e9e871a9928"`);
        await queryRunner.query(`ALTER TABLE "teams_fields_fields" DROP CONSTRAINT "FK_eeb9f45ec38a70dc96234ab9598"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_b5291286325dc7472d0b4c9e6dd"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_5fc9cddc801b973cd9edcdda42a"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_5c5696b2c3c57698f890b2cbbdd"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_be846ad4b43f40acc7034ef7f40"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_bafb08f60d7857f4670c172a6ea"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_c924581ed54ddae034f24955f83"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_a7d98ec4be2c842c6556188cfdc"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "UQ_48c0c32e6247a2de155baeaf980"`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "owners" DROP CONSTRAINT "UQ_df4ef717018c5dc7bd3f4ab0de5"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "teamId"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "UQ_5fc9cddc801b973cd9edcdda42a"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "UQ_c924581ed54ddae034f24955f83"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "addressId"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "usersId" uuid`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "REL_2c6928902becf89437748914cb" UNIQUE ("usersId")`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "teamsId" uuid`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "participantsId" uuid`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "fieldsId" uuid`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "usersId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "teamId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "REL_d1803064187c8f38e57a9c4984" UNIQUE ("teamId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "requestId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "REL_a20f12b66b835efd3e9cdc8efa" UNIQUE ("requestId")`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "adressesId" uuid`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "REL_ce369917874b691538849a790f" UNIQUE ("adressesId")`);
        await queryRunner.query(`ALTER TABLE "fields" ADD "ownersId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a906e42264bcb3e8e9e871a992"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeb9f45ec38a70dc96234ab959"`);
        await queryRunner.query(`DROP TABLE "teams_fields_fields"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`ALTER TABLE "requests" RENAME COLUMN "userId" TO "usersId"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_2c6928902becf89437748914cb0" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_434e93481b53d8007bcf8af8b9d" FOREIGN KEY ("teamsId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_461b2f6f9be2df60f173a0230bc" FOREIGN KEY ("participantsId") REFERENCES "participants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_52bbf2d21bdcac200def516a69d" FOREIGN KEY ("fieldsId") REFERENCES "fields"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_156b59646727c4d7370e17a3454" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_6e912f52513d3edc50f106778fb" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d1803064187c8f38e57a9c4984c" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a20f12b66b835efd3e9cdc8efa0" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_bafb08f60d7857f4670c172a6ea" FOREIGN KEY ("addressId") REFERENCES "adresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_ce369917874b691538849a790f7" FOREIGN KEY ("adressesId") REFERENCES "adresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_d34442903fff451ea18518dbe1e" FOREIGN KEY ("ownersId") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
